apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm
  targetNamespace: kube-system
  valuesContent: |-
    server:
      extraArgs:
      - --insecure
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: kube-system
spec:
  rules:
    - host: "argo.demo.alterus.io"
      http:
        paths:
          - path: /
            backend:
              serviceName: argocd-server 
              servicePort: 80 

