apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: kube-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/alterus-io/demo-app.git 
    targetRevision: master 
